config/routes.rb
Rails.application.routes.draw do
  root "top#index"
  get "/messages", to: "messages#index", as: :messages
  post "/messages", to: "messages#create"
  get "/messages/new", to: "messages#new", as: :new_message
  delete "/messages/:id", to: "messages#destroy", as: :message

  post "/messages/:message_id/favors", to: "favors#create", as: :favors
  delete "/messages/:message_id/favors", to: "favors#destroy"

  get "/login", to: "sessions#new", as: :login
  post "/session", to: "sessions#create", as: :session
  delete "/session", to: "sessions#destroy"

  get "/account", to: "accounts#show", as: :account
  patch "/account", to: "accounts#update"
  get "/account/edit", to: "accounts#edit", as: :edit_account

  get "/users", to: "users#index", as: :users
  get "/users/:id", to: "users#show", as: :user

  post "/users/:id/relationships", to: "relationships#create", as: :user_relationships
  delete "/users/:id/relationships", to: "relationships#destroy"

  get "/api/favors/count", to: "api/favors#count", as: :api_favors_count
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favor.rb
class Favor < ApplicationRecord
  belongs_to :user
  belongs_to :message

  validates :user, uniqueness: { scope: :message }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  has_many :favors

  validates :content, presence: { message: "投稿内容を入力してください。" }
  validates :content, length: { maximum: 140, message: "140文字以内で入力してください。"}

  def favored_by?(user)
    user.in?(self.favors.map(&:user))
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :active_relationships, class_name: "Relationship", foreign_key: "following_id"
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id"
  has_many :followings, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :following
  has_many :favors

  has_one_attached :profile_picture
  attribute :new_profile_picture
  attribute :remove_profile_picture, :boolean

  validates :name, :full_name, presence: { message: "入力必須項目です。" }
  validates :name, uniqueness: { message: "既に使われています。" }

  before_save do
    if new_profile_picture
      self.profile_picture = new_profile_picture
    elsif remove_profile_picture
      self.profile_picture.purge
    end
  end

  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    elsif raw_password.nil?
      self.hashed_password = nil
    end
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.name = params[:user][:name]
    @user.full_name = params[:user][:full_name]
    @user.bio = params[:user][:bio]
    @user.new_profile_picture = params[:user][:new_profile_picture]
    @user.remove_profile_picture = params[:user][:remove_profile_picture]
    if @user.save
      flash.notice = "アカウント情報を更新しました。"
      redirect_to account_path
    else
      flash.now.alert = "アカウント情報の更新に失敗しました。"
      render action: "edit"
    end
  end
end

app/controllers/api/favors_controller.rb
class Api::FavorsController < ApplicationController
  # JavaScript側に「自分が良いね済みか？」と「良いね件数」の2つの情報を返す
  def count
    message = Message.find(params[:message_id])

    am_i_favoring = message.favored_by?(current_user)
    favors_count = message.favors.count

    render json: {
      am_i_favoring: am_i_favoring,
      favors_count: favors_count
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  
  private def current_user
    if session[:user_id]
      @current_user ||=
        User.find(session[:user_id])
    end
  end
  helper_method :current_user

  def authorize
    if !current_user
      flash.alert = "ログインしてください。"
      redirect_to login_path
    end
  end
end

app/controllers/favors_controller.rb
class FavorsController < ApplicationController
  def create
    favor = Favor.create(
      user: current_user,
      message: Message.find(params[:message_id])
    )
    redirect_back fallback_location: messages_path
  end

  def destroy
    favor = Favor.find_by(
      user: current_user,
      message: Message.find(params[:message_id])
    )
    favor.destroy
    redirect_back fallback_location: messages_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    # 自分と自分がフォローしているユーザ達のidをfollowing_iusers_idsに保存
    following_users_ids = current_user.followings.ids + [current_user.id]

    # following_users_idsを使って必要なメッセージのみを取り出して並び替え
    @messages = Message
      .includes(:user)
      .where(user_id: following_users_ids)
      .order(created_at: :desc)
      .page(params[:page]).per(5)
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(user_id: current_user.id)
    @message.content = params[:message][:content]
    if @message.save
      redirect_to messages_path
    else
      render action: "new"
    end
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    flash.notice = "メッセージを削除しました。"
    redirect_to messages_path
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    Relationship.create(
      following_id: current_user.id,
      follower_id: params[:id]
    )
    redirect_back fallback_location: users_path
  end

  def destroy
    Relationship.find_by(
      following_id: current_user.id,
      follower_id: params[:id]
    ).destroy
    redirect_back fallback_location: users_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
  
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user && BCrypt::Password.new(user.hashed_password) == params[:password]
      session[:user_id] = user.id
      flash.notice = "ログインしました。"
      redirect_to messages_path
    else
      flash.now.alert = "ユーザ名またはパスワードが正しくありません。"
      render action: "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash.notice = "ログアウトしました。"
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :authorize
  
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # 現在ログインしているユーザ（自分自身）以外を表示する
    @users = User.where.not(id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.erb
<%= form_for @user, url: account_path do |f| %>
  <div class="form">
    <%= f.label :new_profile_picture, "プロフィール画像" %>
    <%= f.file_field :new_profile_picture %>
    <% if @user.profile_picture.attached? %>
      <div>
        <%= image_tag @user.profile_picture %></br>
        <%= f.check_box :remove_profile_picture %>
        <%= f.label :remove_profile_picture, "プロフィール画像を削除する" %>
      </div>
    <% end %>

    <%= f.label :name, "名前" %>
    <%= f.text_field :name %>
    <div class="error-message"><%= @user.errors[:name].first %></div>

    <%= f.label :full_name, "フルネーム" %>
    <%= f.text_field :full_name %>
    <div class="error-message"><%= @user.errors[:full_name].first %></div>

    <%= f.label :bio, "自己紹介文" %>
    <%= f.text_area :bio %>

    <%= f.submit "プロフィールを更新する" %>
  </div>
<% end %>

app/views/accounts/show.html.erb
<div class="users-show">
  <div class="row">
    <% if @user.profile_picture.attached? %>
      <%= image_tag @user.profile_picture %>
    <% else %>
      <%= image_tag("speak.svg") %>
    <% end %>
    <div>
      <div class="unfollow-button">
        <%= link_to "プロフィールを編集する", edit_account_path %>
      </div>
    </div>
  </div>
  <div class="row">
    <span class="user-full-name"><%= @user.full_name %></span>
  </div>
  <div class="row">
    <span class="user-name">@<%= @user.name %></span>
  </div>
  <div class="row">
    <p class="user-bio"><%= @user.bio %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bergen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <%= render "shared/header" %>
      <div id="container">
        <%= yield %>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
  <div class="posts-index-item">
    <% if message.user.profile_picture.attached? %>
      <%= link_to image_tag(message.user.profile_picture), user_path(message.user) %>
    <% else %>
      <%= link_to image_tag("speak.svg"), user_path(message.user) %>
    <% end %>
    <div>
      <%= link_to message.user.full_name, user_path(message.user), class: "user-full-name" %>
      <%= link_to "@#{message.user.name}", user_path(message.user), class: "user-name" %>
      <br />
      <%= message.content %>
      <br />
      <div class="buttons">
        <% if message.favored_by?(current_user) %>
          <%=
            link_to(
              content_tag(:i, "", class:"fas fa-heart fa-lg"),
              favors_path(message_id: message.id), method: :delete
            )
          %>
        <% else %>
          <%=
            link_to(
              content_tag(:i, "", class:"far fa-heart fa-lg"),
              favors_path(message_id: message.id), method: :post
            )
          %>
        <% end %>
        <%=
          tag.span(
            message.favors.count, class: "favor-count",
            data: {
              message_id: message.id,
              path: api_favors_count_path(message_id: message.id)
            }
          )
        %>
      </div>
    </div>
    <% if message.user == current_user %>
      <%=
        link_to(content_tag(:i, "", class: "fa fa-trash-o fa-lg"),
        message_path(id: message.id), method: :delete,
        data: { confirm: "このメッセージを本当に削除しますか？" })
      %>
    <% end %>
  </div>
<% end %>

<%= paginate @messages %>

app/views/messages/new.html.erb
<h1 class="form-heading">投稿する</h1>

<%= form_for @message do |f| %>
  <div class="form">
    <%= f.text_area :content, cols: 60 %>
    <% f.object.errors[:content].each do |error_message| %>
      <div class="error-message"><%= error_message %></div>
    <% end %>

    <%= f.submit "投稿" %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>Powered by BERGEN &copy; 2019 Your Name</p>
</footer>

app/views/shared/_header.html.erb
<header>
  <span class="logo-mark"><%= link_to "bergen", root_path %></span>
  <%= tag.span flash.notice, class: "notice" if flash.notice %>
  <%= tag.span flash.alert, class: "alert" if flash.alert %>
  <ul class="header-menus">
    <% if current_user %>
      <li><%= link_to "ユーザリスト", users_path %></li>
      <li><%= link_to "メッセージ一覧", messages_path %></li>
      <li><%= link_to "新規投稿", new_message_path %></li>
      <li><%= link_to "アカウント", account_path %></li>
      <li>
        <%= link_to "ログアウト", session_path, method: :delete %>
        <%= tag.small "(#{User.find(session[:user_id]).name})" %>
      </li>
    <% else %>
      <li><%= link_to "ログイン", login_path %></li>
    <% end %>
  </ul>
</header>

app/views/top/index.html.erb
<div class="jumbotron">
  <h1 class="jumbotron-title">Hello, Bergen!</h1>
  <p class="jumbotron-msg">
    Bergenは誰でも簡単にメッセージを投稿できるアプリです。
  </p>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div class="users-index-item">
    <%= link_to "@" + user.name, user_path(user), class: "user-name" %>
    <% if user.id != current_user.id %>
      <% if user.followed_by?(current_user) %>
        <div class="unfollow-button">
          <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete %>
        </div>
      <% else %>
        <div class="follow-button">
          <%= link_to "フォロー", user_relationships_path(user.id), method: :post %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="users-show">
  <div class="row">
    <% if @user.profile_picture.attached? %>
      <%= image_tag @user.profile_picture %>
    <% else %>
      <%= image_tag("speak.svg") %>
    <% end %>
    <div>
      <% if @user.id != current_user.id %>
        <% if @user.followed_by?(current_user) %>
          <div class="unfollow-button">
            <%= link_to "フォロー解除", user_relationships_path(@user.id), method: :delete %>
          </div>
        <% else %>
          <div class="follow-button">
            <%= link_to "フォロー", user_relationships_path(@user.id), method: :post %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <span class="user-full-name"><%= @user.full_name %></span>
  </div>
  <div class="row">
    <span class="user-name">@<%= @user.name %></span>
  </div>
  <div class="row">
    <p class="user-bio"><%= @user.bio %></p>
  </div>
</div>